/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion.Reporte;

/**
 *
 * @author andyv
 */
public class RUsuario extends javax.swing.JPanel {

    /**
     * Creates new form RUsuario
     */
    public RUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbCodigo = new checkbox.JCheckBoxCustom();
        txtDNI = new textfield.TextField();
        cboEst = new combobox.Combobox();
        cbCodigo1 = new checkbox.JCheckBoxCustom();
        cbCodigo2 = new checkbox.JCheckBoxCustom();
        cbCodigo4 = new checkbox.JCheckBoxCustom();
        cbCodigo5 = new checkbox.JCheckBoxCustom();
        cbCodigo6 = new checkbox.JCheckBoxCustom();
        txtCodigo1 = new textfield.TextField();
        cboEst1 = new combobox.Combobox();
        txtCodigo2 = new textfield.TextField();
        txtCodigo3 = new textfield.TextField();
        cboEst2 = new combobox.Combobox();
        txtCodigo4 = new textfield.TextField();
        cboEst3 = new combobox.Combobox();
        cboEst4 = new combobox.Combobox();
        txtCodigo5 = new textfield.TextField();
        cboEst5 = new combobox.Combobox();
        cboEst6 = new combobox.Combobox();
        cboEst7 = new combobox.Combobox();
        cbDia = new checkbox.JCheckBoxCustom();
        cboDia = new combobox.Combobox();
        cboMes = new combobox.Combobox();
        cbMes = new checkbox.JCheckBoxCustom();
        cbYear = new checkbox.JCheckBoxCustom();
        cboAño = new combobox.Combobox();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 102, 255));
        lblTitulo.setText("Usuario");

        jLabel1.setText("Realizar  reporte por:");

        cbCodigo.setText("DNI");
        cbCodigo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbCodigoStateChanged(evt);
            }
        });

        txtDNI.setLabelText("DNI");

        cboEst.setLabeText("Buscar por");
        cboEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEstActionPerformed(evt);
            }
        });

        cbCodigo1.setLabel("Nombre");
        cbCodigo1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbCodigo1StateChanged(evt);
            }
        });

        cbCodigo2.setLabel("Apellido");
        cbCodigo2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbCodigo2StateChanged(evt);
            }
        });

        cbCodigo4.setText("Distrito");
        cbCodigo4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbCodigo4StateChanged(evt);
            }
        });

        cbCodigo5.setText("Sexo");
        cbCodigo5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbCodigo5StateChanged(evt);
            }
        });

        cbCodigo6.setText("Tipo");
        cbCodigo6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbCodigo6StateChanged(evt);
            }
        });

        txtCodigo1.setLabelText("Primer Nombre");

        cboEst1.setLabeText("Buscar por");
        cboEst1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEst1ActionPerformed(evt);
            }
        });

        txtCodigo2.setLabelText("Segundo Nombre");
        txtCodigo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigo2ActionPerformed(evt);
            }
        });

        txtCodigo3.setLabelText("Apellido paterno");

        cboEst2.setLabeText("Buscar por");
        cboEst2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEst2ActionPerformed(evt);
            }
        });

        txtCodigo4.setLabelText("Apellido materno");

        cboEst3.setLabeText("Buscar por");
        cboEst3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEst3ActionPerformed(evt);
            }
        });

        cboEst4.setLabeText("Buscar por");
        cboEst4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEst4ActionPerformed(evt);
            }
        });

        txtCodigo5.setLabelText("Distrito");

        cboEst5.setLabeText("sexo");
        cboEst5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEst5ActionPerformed(evt);
            }
        });

        cboEst6.setLabeText("tipo");
        cboEst6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEst6ActionPerformed(evt);
            }
        });

        cboEst7.setLabeText("tipo");
        cboEst7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEst7ActionPerformed(evt);
            }
        });

        cbDia.setText("Dia");
        cbDia.setToolTipText("");
        cbDia.setActionCommand("");
        cbDia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbDiaStateChanged(evt);
            }
        });

        cboDia.setLabeText("Dia");
        cboDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDiaActionPerformed(evt);
            }
        });

        cboMes.setLabeText("Mes");
        cboMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMesActionPerformed(evt);
            }
        });

        cbMes.setText("Mes");
        cbMes.setActionCommand("");
        cbMes.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbMesStateChanged(evt);
            }
        });

        cbYear.setText("Año");
        cbYear.setActionCommand("");
        cbYear.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbYearStateChanged(evt);
            }
        });

        cboAño.setLabeText("Año");
        cboAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAñoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboEst3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboEst2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboEst, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCodigo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbCodigo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbCodigo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbCodigo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboEst1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCodigo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cboEst4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCodigo5, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                            .addComponent(cboEst5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cboEst6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboEst7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboDia, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboMes, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboAño, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCodigo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCodigo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCodigo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboEst, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboEst4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboEst1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboEst2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboEst3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(cboEst5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboEst6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboEst7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboDia, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboMes, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboAño, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbCodigoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbCodigoStateChanged

    }//GEN-LAST:event_cbCodigoStateChanged

    private void cboEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEstActionPerformed

    private void cbCodigo1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbCodigo1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCodigo1StateChanged

    private void cbCodigo2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbCodigo2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCodigo2StateChanged

    private void cbCodigo4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbCodigo4StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCodigo4StateChanged

    private void cbCodigo5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbCodigo5StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCodigo5StateChanged

    private void cbCodigo6StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbCodigo6StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCodigo6StateChanged

    private void cboEst1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEst1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEst1ActionPerformed

    private void cboEst2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEst2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEst2ActionPerformed

    private void cboEst3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEst3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEst3ActionPerformed

    private void txtCodigo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigo2ActionPerformed

    private void cboEst4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEst4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEst4ActionPerformed

    private void cboEst5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEst5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEst5ActionPerformed

    private void cboEst6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEst6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEst6ActionPerformed

    private void cboEst7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEst7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEst7ActionPerformed

    private void cbDiaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbDiaStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDiaStateChanged

    private void cboDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDiaActionPerformed

    private void cboMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMesActionPerformed

    private void cbMesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbMesStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMesStateChanged

    private void cbYearStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbYearStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbYearStateChanged

    private void cboAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboAñoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private checkbox.JCheckBoxCustom cbCodigo;
    private checkbox.JCheckBoxCustom cbCodigo1;
    private checkbox.JCheckBoxCustom cbCodigo2;
    private checkbox.JCheckBoxCustom cbCodigo4;
    private checkbox.JCheckBoxCustom cbCodigo5;
    private checkbox.JCheckBoxCustom cbCodigo6;
    private checkbox.JCheckBoxCustom cbDia;
    private checkbox.JCheckBoxCustom cbMes;
    private checkbox.JCheckBoxCustom cbYear;
    protected combobox.Combobox cboAño;
    protected combobox.Combobox cboDia;
    protected combobox.Combobox cboEst;
    protected combobox.Combobox cboEst1;
    protected combobox.Combobox cboEst2;
    protected combobox.Combobox cboEst3;
    protected combobox.Combobox cboEst4;
    protected combobox.Combobox cboEst5;
    protected combobox.Combobox cboEst6;
    protected combobox.Combobox cboEst7;
    protected combobox.Combobox cboMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTitulo;
    protected textfield.TextField txtCodigo1;
    protected textfield.TextField txtCodigo2;
    protected textfield.TextField txtCodigo3;
    protected textfield.TextField txtCodigo4;
    protected textfield.TextField txtCodigo5;
    protected textfield.TextField txtDNI;
    // End of variables declaration//GEN-END:variables
}
